# Generated by Django 5.1.2 on 2024-11-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='signature',
            field=models.CharField(default='Khanya', max_length=140),
        ),
    ]
